RedFishingTilesFront:: INCBIN "gfx/overworld/red_fish_front.2bpp"
RedFishingTilesBack::  INCBIN "gfx/overworld/red_fish_back.2bpp"
RedFishingTilesSide::  INCBIN "gfx/overworld/red_fish_side.2bpp"
RedFishingRodTiles::   INCBIN "gfx/overworld/fishing_rod.2bpp"
RedFFishingTilesFront:: INCBIN "gfx/overworld/redF_fishing_tile_front.2bpp"
RedFFishingTilesBack::  INCBIN "gfx/overworld/redF_fishing_tile_back.2bpp"
RedFFishingTilesSide::  INCBIN "gfx/overworld/redF_fishing_tile_side.2bpp"
